FROM node:24.11.1-slim AS base

RUN corepack enable pnpm

WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml turbo.json ./

COPY front/package.json ./front/

RUN pnpm install 

COPY front ./front



ENV NODE_ENV=development
ENV NEXT_TELEMETRY_DISABLED=1
ENV WATCHPACK_POLLING=true
ENV CHOKIDAR_USEPOLLING=true

EXPOSE 3001

WORKDIR /app/front

CMD ["pnpm", "run", "dev"]