sonar.projectKey=alice-444_ls_app
sonar.organization=hola-solar

# Exclusions
sonar.exclusions=**/node_modules/**,**/.next/**,**/dist/**,**/build/**,**/.turbo/**,**/coverage/**,**/prisma/generated/**,**/*.min.js,**/*.min.css,**/public/**,**/*.d.ts,**/pnpm-lock.yaml
