FROM node:24.11.1-slim AS base

RUN apt-get update -y && \
    apt-get install -y openssl ca-certificates && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY ../../back .

RUN corepack enable pnpm
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

COPY ../../back/dev.sh /dev.sh
RUN chmod +x /dev.sh

EXPOSE 3000

ENTRYPOINT ["/dev.sh"]