name: Tests 🧪

on:
  workflow_call:
  push:
    branches:
      - main
      - prod
      - dev
  pull_request:
    branches:
      - main
      - prod
      - dev

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  run-tests:
    name: Run All Tests
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PNPM and Node.js
        uses: digi-fry/setup-pnpm-node-action@v1
        with:
          node-version: "24"

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm test
        env:
          NODE_ENV: test
          CI: true
          DATABASE_URL: postgresql://user:password@localhost:5432/dbname?schema=public
